---
- name: Update cache if on Debian or Ubuntu
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'
  become: yes

- name: Install the SSH server
  package:
    name: openssh-server
    state: present
  become: yes

- name: Create automation user
  user:
    name: "{{ automation_user }}"
  become: yes

- name: Let the automation user sudo without a password
  template:
    src: files/sudoers_custom
    dest: "/etc/sudoers.d/{{ automation_user }}"
    validate: 'visudo -cf %s'
  changed_when: false
  become: yes
  notify:
    - restart_ssh

- name: Manage authorized SSH key to automation user
  authorized_key:
    exclusive: yes
    user: "{{ automation_user }}"
    key: "{{ item }}"
  with_items: {{ ansible_public_keys_path }}
  no_log: true
  tags: sshkeys
  become: yes

- name: Make sure the ssh service is initialized
  service:
    name: sshd
    state: started
    enabled: yes
  become: yes

- name: Allow ansible user only with key
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      Match User "{{ automation_user }}"
      PasswordAuthentication no
  become: yes
  notify:
    - restart_ssh
